#!/bin/sh
#MISE description="Lint gofmt"

set -eu

files="$(gofmt -l -s .)"

if [ -n "$files" ]; then
  echo "These .go files need to be formatted:"
  echo ""
  echo "$files"
  echo ""
  echo "To fix: mise run fmt"
  exit 1
fi
