#!/bin/sh
#MISE description="Check go.mod and go.sum are tidy"

set -eu

go mod tidy

status="$(git status --porcelain=v1 go.mod go.sum 2>/dev/null)"
if [ -n "$status" ]; then
  echo "go module files modified, please commit the result of 'go mod tidy'!"
  echo "$status"
  exit 1
fi
